### ISSUE TITLE
cannot start on FreeBSD

### ISSUE THREAD

**Issue by cdburgess75** [DaVieS007/ASPF#8]
eval: /usr/local/www/nginx/ASPF/CLI-Worker/aspf.php: not found

I run service aspf start and get this,  the file does exist with correct permission.  I also see a lot of references to /Storage Systems  in the php file,  that is not a valid directory

**Comment by DaVieS007** [comment]
Yes, becuase ASPF came with MVCP (Mass Virtualhost Control Panel) and it has a bundle setup and virtual appliances, ASPF Standalone not yet released and maybe hardcoded into binaries.
